=== MariuszKam/Rental/src/main/resources/RentalDeal.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="RentalDeal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
                <xs:element name="customer" type="CustomerType"/>
                <xs:element name="startRental" type="xs:dateTime"/>
                <xs:element name="endRental" type="xs:dateTime"/>
                <xs:element name="totalCost" type="xs:decimal"/>
                <xs:element name="employee" type="EmployeeType"/>
                <xs:element name="status" type="StatusType"/>
                <xs:element name="vehicles" type="VehicleListType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="phoneNumber" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="contract" type="ContractType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContractType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="startContract" type="xs:dateTime"/>
            <xs:element name="endContract" type="xs:dateTime"/>
            <xs:element name="salary" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StatusType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="status" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VehicleType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="vehicleType" type="VehicleTypeType"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="registrationNumber" type="xs:string"/>
            <xs:element name="currentKilometers" type="xs:long"/>
            <xs:element name="available" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VehicleTypeType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="typeName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VehicleListType">
        <xs:sequence>
            <xs:element name="vehicle" type="VehicleType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MariuszKam/Rental/src/main/resources/RentalDeal.xml
<RentalDeal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="RentalDeal.xsd">
    <id>1</id>
    <customer>
        <id>1</id>
        <firstName>Darek</firstName>
        <lastName>Dark</lastName>
        <phoneNumber>586-856-456</phoneNumber>
        <email>d.dark@gmail.com</email>
        <address>Main st 34</address>
    </customer>
    <startRental>2024-01-09T12:00:00</startRental>
    <endRental>2024-01-10T12:00:00</endRental>
    <totalCost>100.00</totalCost>
    <employee>
        <id>1</id>
        <firstName>Sam</firstName>
        <lastName>Wrecked</lastName>
        <position>Seller</position>
        <contract>
            <id>1</id>
            <startDate>2023-02-23T00:00:00</startDate>
            <endDate>2026-02-24T00:00:00</endDate>
            <amount>2450.90</amount>
        </contract>
    </employee>
    <status>
        <id>1</id>
        <status>Pending</status>
    </status>
    <vehicles>
        <vehicle>
            <id>1</id>
            <vehicleType>
                <id>1</id>
                <name>Sedan</name>
            </vehicleType>
            <model>Audi A3</model>
            <registrationNumber>ZS82564</registrationNumber>
            <currentKilometers>134003</currentKilometers>
            <available>true</available>
        </vehicle>
        <vehicle>
            <id>2</id>
            <vehicleType>
                <id>1</id>
                <name>Sedan</name>
            </vehicleType>
            <model>Volkswagen Passat B6</model>
            <registrationNumber>ZS56197</registrationNumber>
            <currentKilometers>156879</currentKilometers>
            <available>true</available>
        </vehicle>
        <!-- Pickup -->
        <vehicle>
            <id>3</id>
            <vehicleType>
                <id>2</id>
                <name>Pickup</name>
            </vehicleType>
            <model>Ford Ranger</model>
            <registrationNumber>ZS43715</registrationNumber>
            <currentKilometers>4173659</currentKilometers>
            <available>true</available>
        </vehicle>
        <vehicle>
            <id>4</id>
            <vehicleType>
                <id>2</id>
                <name>Pickup</name>
            </vehicleType>
            <model>Volkswagen Amarok</model>
            <registrationNumber>ZS71485</registrationNumber>
            <currentKilometers>84578925</currentKilometers>
            <available>true</available>
        </vehicle>
    </vehicles>
</RentalDeal>
